name: gs-decoder
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - plyfile
  - python=3.10
  - cudatoolkit=11.8
  - pip
  - click
  - pillow
  - scipy
  - pytorch-cuda=11.8
  - torchaudio
  - torchvision
  - requests
  - tqdm
  - ninja=1.10.2
  - matplotlib
  - imageio
  - opencv
  - scikit-learn
  - scikit-image
  - pip:
    - pyopengl
    - imageio-ffmpeg
    - pyspng
    - psutil
    - mrcfile
    - scikit-image
    - tensorboard
    - trimesh==4.1.4
    - gaussian_splatting/submodules/diff-gaussian-rasterization
    - gaussian_splatting/submodules/simple-knn
    - wandb
    - smplx
    - chumpy==0.70
    - numpy==1.23.1
    - pytorch_msssim
    - trimesh